export const Data = {
  daraz: [
    {
      order_id: 1,
      company_id: 1,
      customer_name: 'Ali Khan',
      product: 'Mobile Phone',
      quantity: 1,
      price: 150.0,
      status: 'Shipped',
      order_date: '2024-12-01',
      delivery_date: '2024-12-05'
    },
    {
      order_id: 2,
      company_id: 1,
      customer_name: 'Sara Ahmed',
      product: 'Laptop Bag',
      quantity: 1,
      price: 25.0,
      status: 'Delivered',
      order_date: '2024-11-20',
      delivery_date: '2024-11-25'
    },
    {
      order_id: 3,
      company_id: 1,
      customer_name: 'Zain Ali',
      product: 'Bluetooth Speaker',
      quantity: 2,
      price: 50.0,
      status: 'Pending',
      order_date: '2024-12-05',
      delivery_date: null
    },
    {
      order_id: 4,
      company_id: 1,
      customer_name: 'Noor Fatima',
      product: 'Wrist Watch',
      quantity: 1,
      price: 30.0,
      status: 'Cancelled',
      order_date: '2024-12-08',
      delivery_date: null
    },
    {
      order_id: 5,
      company_id: 1,
      customer_name: 'Hassan Raza',
      product: 'Tablet',
      quantity: 1,
      price: 300.0,
      status: 'Delivered',
      order_date: '2024-12-01',
      delivery_date: '2024-12-04'
    },
    {
      order_id: 6,
      company_id: 1,
      customer_name: 'Iqra Malik',
      product: 'Gaming Mouse',
      quantity: 1,
      price: 20.0,
      status: 'Shipped',
      order_date: '2024-12-03',
      delivery_date: '2024-12-06'
    },
    {
      order_id: 7,
      company_id: 1,
      customer_name: 'Ahmed Khan',
      product: 'Power Bank',
      quantity: 1,
      price: 40.0,
      status: 'Pending',
      order_date: '2024-12-10',
      delivery_date: null
    },
    {
      order_id: 8,
      company_id: 1,
      customer_name: 'Sana Ali',
      product: 'Fitness Tracker',
      quantity: 1,
      price: 70.0,
      status: 'Delivered',
      order_date: '2024-11-30',
      delivery_date: '2024-12-02'
    },
    {
      order_id: 9,
      company_id: 1,
      customer_name: 'Bilal Shah',
      product: 'Wireless Earbuds',
      quantity: 1,
      price: 60.0,
      status: 'Cancelled',
      order_date: '2024-12-07',
      delivery_date: null
    },
    {
      order_id: 10,
      company_id: 1,
      customer_name: 'Rabia Noor',
      product: 'Smartphone Case',
      quantity: 2,
      price: 10.0,
      status: 'Delivered',
      order_date: '2024-12-12',
      delivery_date: '2024-12-14'
    },
    {
      order_id: 11,
      company_id: 1,
      customer_name: 'Usman Tariq',
      product: 'Action Camera',
      quantity: 1,
      price: 250.0,
      status: 'Shipped',
      order_date: '2024-12-09',
      delivery_date: '2024-12-15'
    },
    {
      order_id: 12,
      company_id: 1,
      customer_name: 'Kiran Fatima',
      product: 'Tripod Stand',
      quantity: 1,
      price: 35.0,
      status: 'Pending',
      order_date: '2024-12-14',
      delivery_date: null
    },
    {
      order_id: 13,
      company_id: 1,
      customer_name: 'Omar Khan',
      product: 'Gaming Keyboard',
      quantity: 1,
      price: 75.0,
      status: 'Delivered',
      order_date: '2024-11-25',
      delivery_date: '2024-11-29'
    },
    {
      order_id: 14,
      company_id: 1,
      customer_name: 'Anum Tariq',
      product: 'VR Headset',
      quantity: 1,
      price: 200.0,
      status: 'Shipped',
      order_date: '2024-12-11',
      delivery_date: '2024-12-16'
    },
    {
      order_id: 15,
      company_id: 1,
      customer_name: 'Ali Abbas',
      product: 'Graphic Tablet',
      quantity: 1,
      price: 100.0,
      status: 'Cancelled',
      order_date: '2024-12-01',
      delivery_date: null
    },
    {
      order_id: 16,
      company_id: 1,
      customer_name: 'Fatima Zahra',
      product: 'Noise Cancelling Headphones',
      quantity: 1,
      price: 150.0,
      status: 'Delivered',
      order_date: '2024-12-13',
      delivery_date: '2024-12-18'
    },
    {
      order_id: 17,
      company_id: 1,
      customer_name: 'Zoya Malik',
      product: 'External Hard Drive',
      quantity: 1,
      price: 120.0,
      status: 'Shipped',
      order_date: '2024-12-17',
      delivery_date: '2024-12-21'
    },
    {
      order_id: 18,
      company_id: 1,
      customer_name: 'Hamza Tariq',
      product: 'Laptop Cooling Pad',
      quantity: 1,
      price: 30.0,
      status: 'Pending',
      order_date: '2024-12-19',
      delivery_date: null
    },
    {
      order_id: 19,
      company_id: 1,
      customer_name: 'Rida Khan',
      product: 'Wireless Charger',
      quantity: 1,
      price: 25.0,
      status: 'Delivered',
      order_date: '2024-12-20',
      delivery_date: '2024-12-22'
    },
    {
      order_id: 20,
      company_id: 1,
      customer_name: 'Hassan Ali',
      product: 'USB Flash Drive',
      quantity: 1,
      price: 15.0,
      status: 'Shipped',
      order_date: '2024-12-21',
      delivery_date: '2024-12-23'
    }
  ],
  amazon: [
    {
      order_id: 1,
      company_id: 1,
      customer_name: 'Ali Khan',
      product: 'Mobile Phone',
      quantity: 1,
      price: 150.0,
      status: 'Shipped',
      order_date: '2024-12-01',
      delivery_date: '2024-12-05'
    },
    {
      order_id: 2,
      company_id: 1,
      customer_name: 'Sara Ahmed',
      product: 'Laptop Bag',
      quantity: 1,
      price: 25.0,
      status: 'Delivered',
      order_date: '2024-11-20',
      delivery_date: '2024-11-25'
    },
    {
      order_id: 3,
      company_id: 1,
      customer_name: 'Zain Ali',
      product: 'Bluetooth Speaker',
      quantity: 2,
      price: 50.0,
      status: 'Pending',
      order_date: '2024-12-05',
      delivery_date: null
    },
    {
      order_id: 4,
      company_id: 1,
      customer_name: 'Noor Fatima',
      product: 'Wrist Watch',
      quantity: 1,
      price: 30.0,
      status: 'Cancelled',
      order_date: '2024-12-08',
      delivery_date: null
    },
    {
      order_id: 5,
      company_id: 1,
      customer_name: 'Hassan Raza',
      product: 'Tablet',
      quantity: 1,
      price: 300.0,
      status: 'Delivered',
      order_date: '2024-12-01',
      delivery_date: '2024-12-04'
    },
    {
      order_id: 6,
      company_id: 1,
      customer_name: 'Iqra Malik',
      product: 'Gaming Mouse',
      quantity: 1,
      price: 20.0,
      status: 'Shipped',
      order_date: '2024-12-03',
      delivery_date: '2024-12-06'
    },
    {
      order_id: 7,
      company_id: 1,
      customer_name: 'Ahmed Khan',
      product: 'Power Bank',
      quantity: 1,
      price: 40.0,
      status: 'Pending',
      order_date: '2024-12-10',
      delivery_date: null
    },
    {
      order_id: 8,
      company_id: 1,
      customer_name: 'Sana Ali',
      product: 'Fitness Tracker',
      quantity: 1,
      price: 70.0,
      status: 'Delivered',
      order_date: '2024-11-30',
      delivery_date: '2024-12-02'
    },
    {
      order_id: 9,
      company_id: 1,
      customer_name: 'Bilal Shah',
      product: 'Wireless Earbuds',
      quantity: 1,
      price: 60.0,
      status: 'Cancelled',
      order_date: '2024-12-07',
      delivery_date: null
    },
    {
      order_id: 10,
      company_id: 1,
      customer_name: 'Rabia Noor',
      product: 'Smartphone Case',
      quantity: 2,
      price: 10.0,
      status: 'Delivered',
      order_date: '2024-12-12',
      delivery_date: '2024-12-14'
    },
    {
      order_id: 11,
      company_id: 1,
      customer_name: 'Usman Tariq',
      product: 'Action Camera',
      quantity: 1,
      price: 250.0,
      status: 'Shipped',
      order_date: '2024-12-09',
      delivery_date: '2024-12-15'
    },
    {
      order_id: 12,
      company_id: 1,
      customer_name: 'Kiran Fatima',
      product: 'Tripod Stand',
      quantity: 1,
      price: 35.0,
      status: 'Pending',
      order_date: '2024-12-14',
      delivery_date: null
    },
    {
      order_id: 13,
      company_id: 1,
      customer_name: 'Omar Khan',
      product: 'Gaming Keyboard',
      quantity: 1,
      price: 75.0,
      status: 'Delivered',
      order_date: '2024-11-25',
      delivery_date: '2024-11-29'
    },
    {
      order_id: 14,
      company_id: 1,
      customer_name: 'Anum Tariq',
      product: 'VR Headset',
      quantity: 1,
      price: 200.0,
      status: 'Shipped',
      order_date: '2024-12-11',
      delivery_date: '2024-12-16'
    },
    {
      order_id: 15,
      company_id: 1,
      customer_name: 'Ali Abbas',
      product: 'Graphic Tablet',
      quantity: 1,
      price: 100.0,
      status: 'Cancelled',
      order_date: '2024-12-01',
      delivery_date: null
    },
    {
      order_id: 16,
      company_id: 1,
      customer_name: 'Fatima Zahra',
      product: 'Noise Cancelling Headphones',
      quantity: 1,
      price: 150.0,
      status: 'Delivered',
      order_date: '2024-12-13',
      delivery_date: '2024-12-18'
    },
    {
      order_id: 17,
      company_id: 1,
      customer_name: 'Zoya Malik',
      product: 'External Hard Drive',
      quantity: 1,
      price: 120.0,
      status: 'Shipped',
      order_date: '2024-12-17',
      delivery_date: '2024-12-21'
    },
    {
      order_id: 18,
      company_id: 1,
      customer_name: 'Hamza Tariq',
      product: 'Laptop Cooling Pad',
      quantity: 1,
      price: 30.0,
      status: 'Pending',
      order_date: '2024-12-19',
      delivery_date: null
    },
    {
      order_id: 19,
      company_id: 1,
      customer_name: 'Rida Khan',
      product: 'Wireless Charger',
      quantity: 1,
      price: 25.0,
      status: 'Delivered',
      order_date: '2024-12-20',
      delivery_date: '2024-12-22'
    },
    {
      order_id: 20,
      company_id: 1,
      customer_name: 'Hassan Ali',
      product: 'USB Flash Drive',
      quantity: 1,
      price: 15.0,
      status: 'Shipped',
      order_date: '2024-12-21',
      delivery_date: '2024-12-23'
    }
  ],
  foodpanda: [
    {
      order_id: 3,
      company_id: 1,
      customer_name: 'Zain Ali',
      product: 'Bluetooth Speaker',
      quantity: 2,
      price: 50.0,
      status: 'Pending',
      order_date: '2024-12-05',
      delivery_date: null
    },
    {
      order_id: 4,
      company_id: 1,
      customer_name: 'Noor Fatima',
      product: 'Wrist Watch',
      quantity: 1,
      price: 30.0,
      status: 'Cancelled',
      order_date: '2024-12-08',
      delivery_date: null
    },
    {
      order_id: 5,
      company_id: 1,
      customer_name: 'Hassan Raza',
      product: 'Tablet',
      quantity: 1,
      price: 300.0,
      status: 'Delivered',
      order_date: '2024-12-01',
      delivery_date: '2024-12-04'
    },
    {
      order_id: 6,
      company_id: 1,
      customer_name: 'Iqra Malik',
      product: 'Gaming Mouse',
      quantity: 1,
      price: 20.0,
      status: 'Shipped',
      order_date: '2024-12-03',
      delivery_date: '2024-12-06'
    },
    {
      order_id: 7,
      company_id: 1,
      customer_name: 'Ahmed Khan',
      product: 'Power Bank',
      quantity: 1,
      price: 40.0,
      status: 'Pending',
      order_date: '2024-12-10',
      delivery_date: null
    },
    {
      order_id: 17,
      company_id: 1,
      customer_name: 'Zoya Malik',
      product: 'External Hard Drive',
      quantity: 1,
      price: 120.0,
      status: 'Shipped',
      order_date: '2024-12-17',
      delivery_date: '2024-12-21'
    },
    {
      order_id: 18,
      company_id: 1,
      customer_name: 'Hamza Tariq',
      product: 'Laptop Cooling Pad',
      quantity: 1,
      price: 30.0,
      status: 'Pending',
      order_date: '2024-12-19',
      delivery_date: null
    },
    {
      order_id: 19,
      company_id: 1,
      customer_name: 'Rida Khan',
      product: 'Wireless Charger',
      quantity: 1,
      price: 25.0,
      status: 'Delivered',
      order_date: '2024-12-20',
      delivery_date: '2024-12-22'
    },
    {
      order_id: 20,
      company_id: 1,
      customer_name: 'Hassan Ali',
      product: 'USB Flash Drive',
      quantity: 1,
      price: 15.0,
      status: 'Shipped',
      order_date: '2024-12-21',
      delivery_date: '2024-12-23'
    },
    {
      order_id: 15,
      company_id: 1,
      customer_name: 'Ali Abbas',
      product: 'Graphic Tablet',
      quantity: 1,
      price: 100.0,
      status: 'Cancelled',
      order_date: '2024-12-01',
      delivery_date: null
    },
    {
      order_id: 16,
      company_id: 1,
      customer_name: 'Fatima Zahra',
      product: 'Noise Cancelling Headphones',
      quantity: 1,
      price: 150.0,
      status: 'Delivered',
      order_date: '2024-12-13',
      delivery_date: '2024-12-18'
    },
    {
      order_id: 17,
      company_id: 1,
      customer_name: 'Zoya Malik',
      product: 'External Hard Drive',
      quantity: 1,
      price: 120.0,
      status: 'Shipped',
      order_date: '2024-12-17',
      delivery_date: '2024-12-21'
    },
    {
      order_id: 18,
      company_id: 1,
      customer_name: 'Hamza Tariq',
      product: 'Laptop Cooling Pad',
      quantity: 1,
      price: 30.0,
      status: 'Pending',
      order_date: '2024-12-19',
      delivery_date: null
    },
    {
      order_id: 19,
      company_id: 1,
      customer_name: 'Rida Khan',
      product: 'Wireless Charger',
      quantity: 1,
      price: 25.0,
      status: 'Delivered',
      order_date: '2024-12-20',
      delivery_date: '2024-12-22'
    },
    {
      order_id: 55,
      company_id: 1,
      customer_name: 'Hassan Raza',
      product: 'Tablet',
      quantity: 1,
      price: 300.0,
      status: 'Delivered',
      order_date: '2024-12-01',
      delivery_date: '2024-12-04'
    },
    {
      order_id: 89,
      company_id: 1,
      customer_name: 'Iqra Malik',
      product: 'Gaming Mouse',
      quantity: 1,
      price: 20.0,
      status: 'Shipped',
      order_date: '2024-12-03',
      delivery_date: '2024-12-06'
    },
    {
      order_id: 90,
      company_id: 1,
      customer_name: 'Ahmed Khan',
      product: 'Power Bank',
      quantity: 1,
      price: 40.0,
      status: 'Pending',
      order_date: '2024-12-10',
      delivery_date: null
    },
    {
      order_id: 8,
      company_id: 1,
      customer_name: 'Sana Ali',
      product: 'Fitness Tracker',
      quantity: 1,
      price: 70.0,
      status: 'Delivered',
      order_date: '2024-11-30',
      delivery_date: '2024-12-02'
    },
    {
      order_id: 9,
      company_id: 1,
      customer_name: 'Bilal Shah',
      product: 'Wireless Earbuds',
      quantity: 1,
      price: 60.0,
      status: 'Cancelled',
      order_date: '2024-12-07',
      delivery_date: null
    },
    {
      order_id: 10,
      company_id: 1,
      customer_name: 'Rabia Noor',
      product: 'Smartphone Case',
      quantity: 2,
      price: 10.0,
      status: 'Delivered',
      order_date: '2024-12-12',
      delivery_date: '2024-12-14'
    },
    {
      order_id: 11,
      company_id: 1,
      customer_name: 'Usman Tariq',
      product: 'Action Camera',
      quantity: 1,
      price: 250.0,
      status: 'Shipped',
      order_date: '2024-12-09',
      delivery_date: '2024-12-15'
    }
  ]
}
